- job:
    name: czechlight-gammarus-dashboard
    parent: run-ci-build-sh-f33
    success-url: docs/index.html
    nodeset:
      nodes:
        - name: w
          label: f31-small

- project:
    check:
      jobs:
        - czechlight-gammarus-dashboard
